### ISSUE TITLE
RichTextRenderer::Renderer#render should not raise an error when provided argument nil

### ISSUE THREAD

**Issue by earoberson** [contentful/rich-text-renderer.rb#22]
Objects in contentful with rich text fields where no rich text is added at all will cause an error when attempting to render rich text with this gem. 

This is caused by https://github.com/contentful/rich-text-renderer.rb/blob/master/lib/rich_text_renderer/base_node_renderer.rb#L13

But https://github.com/contentful/rich-text-renderer.rb/blob/master/lib/rich_text_renderer/renderer.rb#L13 makes it seem that nil should be an accepted arg.

PR: https://github.com/contentful/rich-text-renderer.rb/pull/21

**Comment by earoberson** [comment]
any movement on this? 

The issue is either that the contentful gem returns `nil` for rich text fields when there is no content at all, or that this gem cannot handle `nil` nodes. I've added the PR here to handle `nil` nodes.

**Comment by rubydog** [comment]
fixed in #21
